server:
  port: 8086
  
spring:
  application:
    name : CONFIGSERVER

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka/   
    